In [10]:
import numpy as np

import pandas as pd

from pandas import Series, DataFrame

import matplotlib.pyplot as plt

import sklearn.datasets as datesets

from sklearn.tree import DecisionTreeClassifier

from sklearn import metrics

from sklearn.model_selection import train_test_split

In [2]:
data = pd.read_csv('decision.csv', encoding='utf-8',sep=' ')
data.head()

,user_id,age,net_age,neto_dur,chrg_dur,sms_bill_cnt,flux_fee,iset_flux,arpu,acct_balance,extend_paydate_days,last_year_owe_cnt,last_year_complain_cnt,ordered_prodect_cnt,circle_nou,churn_label
0,8408056510,31,25,42,42,16,2717,10240,21383,4162,30,0,0,3,4,0
1,8627971378,37,23,97,42,21,2382,1024,7847,5884,47,5,0,1,4,0
2,8707700881,35,20,73,27,4,2152,300,1941,3358,40,0,0,4,2,1
3,8404003205,42,15,97,27,21,2024,200,2656,2487,70,0,0,1,6,0
4,8701397825,39,21,71,8,15,2336,10240,9954,3052,70,3,3,2,6,0

In [6]:
col_dicts = {}

cols = data.columns.values.tolist()

df = data.loc[:,cols[1:]]

print(df.shape)

X = df.loc[:,cols[1:-1]]

print(X.info)

y = df[cols[-1]]

(1000000, 15)
<bound method DataFrame.info of         age  net_age  neto_dur  chrg_dur  sms_bill_cnt  flux_fee  iset_flux  \
0        31       25        42        42            16      2717      10240
1        37       23        97        42            21      2382       1024
2        35       20        73        27             4      2152        300
3        42       15        97        27            21      2024        200
4        39       21        71         8            15      2336      10240
5        29        1       103        22            17      1787        200
6        31       30        43        37            21      1435       1536
7        39       56        59        26            10      1493        500
8        42       47        40        20            10      2837       5120
9        35       35        83        41             8      2941      10240
10       49       18        46        23            10      1866       2048
11       29       14        86        36            20      2865      10240
12       30       43        57        39            16      1659       1024
13       57       34        44        31             7      1846       4096
14       31       36        43        35            22      1127        300
15       35       30        82        34            18      2494      10240
16       57       46       108        34            26      1365       4096
17       27       29        56        25            10      2098       1024
18       24       32        56        50            17      1607        200
19       22       50        51        36            16      3216        500
20       57       24        69        13            11      1678        300
21       33       56        48        30             9      2085       1536
22       50       15        51        35             8      1453       4096
23       41       40        86        28            21      1587       2048
24       25       13        43        43            14      1300        500
25       18       32        82        26            10      1975        500
26       47       43        92        14            21      2783       1024
27       43       39        46        39             7      2854        500
28       32       21        47        15            21      1885        200
29       46       21        51        23            14      3297       1536
...     ...      ...       ...       ...           ...       ...        ...
999970   44       51        39        22            14      1743       5120
999971   24       21        83        30            13      2238       1536
999972   36       59        58        32            17      2226       1024
999973   34       43        60        35            12      2003      10240
999974   35       37        51        10            20      2107       4096
999975   26       24        49        31             9       956        300
999976   36       30        71        44            14      2357       1024
999977   37       61        53        26             8      1784        300
999978   22       48        47        17            10      1661      10240
999979   25       31        63        31             9      1739       1536
999980   41       28        57        28            11      1941      10240
999981   33       34        55        19            10      1941       4096
999982   21       26        58        22             1      1746       1024
999983   36       58        57        23            15        78       5120
999984   37       39        45        38            15      2661      10240
999985   61       13        82        35            25      1182        300
999986   43       54        77        27            13      1775       2048
999987   39       37        74        22            10      2468        500
999988   37       34        44        31            24      2772        500
999989   40        7        53        29            10      1819       2048
999990   21       41        69        32            25      1429       2048
999991   23       36        36        45            24      2291       2048
999992   40        6        95        30             8      2336       5120
999993   23       35        29        26            16      2839       4096
999994   33        9        47        43            17      1729      10240
999995   38       41        63        38            20      3049       4096
999996   38       31        52        28             6      2167       1536
999997   27       14        47        30            22      2070      10240
999998   41       36        79        24            18      2563       1536
999999   46       44        78        42             5      2583      10240

         arpu  acct_balance  extend_paydate_days  last_year_owe_cnt  \
0       21383          4162                   30                  0
1        7847          5884                   47                  5
2        1941          3358                   40                  0
3        2656          2487                   70                  0
4        9954          3052                   70                  3
5        1623          3536                   12                  3
6        2395          2940                   31                  4
7        4016          5097                   45                  0
8       14216          7680                   12                  2
9       19097          6385                   60                  0
10      10978          1921                   51                  0
11      23802          3344                   34                  0
12       4235          5484                   24                  0
13       8471          5133                   22                  0
14       2770          2708                   47                  1
15      30018          3720                   12                  0
16       7318          5555                   13                  0
17       5550          2863                   55                  0
18       2566          1505                    8                  0
19       4718          7484                   69                  0
20       2903          2418                    1                  0
21       6235          5880                   79                  2
22      14614          5271                   75                  0
23       5864          1720                   11                  0
24       6420          4557                   25                  0
25       3899          7511                   30                  0
26       3963           870                   60                  0
27       2084          3747                   76                  2
28       2161           730                   29                  0
29       7510          4389                   46                  0
...       ...           ...                  ...                ...
999970   3717           215                   33                  4
999971   4761          4061                    2                  1
999972   4684          5346                   57                  1
999973  21175          2293                   43                  0
999974   8019          5027                   46                  0
999975   3268          3305                   73                  0
999976   3590          3531                   74                  0
999977   3312          1962                   52                  0
999978  31421          7473                   14                  0
999979   5771          2687                   40                  0
999980  23448          5763                   22                  0
999981  20443          4976                   29                  0
999982   3248          6738                   80                  1
999983   9446          5751                   29                  0
999984  17602          2038                   13                  0
999985   2243          2083                   26                  0
999986   4421          1548                    3                  0
999987   3400          1115                   39                  0
999988   4373          5424                   21                  2
999989  10802          4137                   16                  0
999990   9462          4198                   25                  0
999991  11743          5696                    8                  0
999992  12331          1991                   37                  0
999993   8879          3504                   54                  0
999994  21089          3738                   14                  0
999995   6399          2103                   55                  0
999996   6471          1752                   42                  1
999997  27989          4292                   78                  0
999998   5256          5621                    4                  0
999999  27704          3078                   17                  0

        last_year_complain_cnt  ordered_prodect_cnt  circle_nou
0                            0                    3           4
1                            0                    1           4
2                            0                    4           2
3                            0                    1           6
4                            3                    2           6
5                            0                    1           5
6                            1                    4           0
7                            0                    2           1
8                            1                    5           5
9                            4                    5           2
10                           0                    1           3
11                           0                    1           4
12                           0                    1           5
13                           0                    1           3
14                           0                    4           2
15                           0                    6           4
16                           0                    3           1
17                           0                    2           5
18                           0                    3           2
19                           0                    6           5
20                           0                    5           1
21                           0                    5           3
22                           0                    6           1
23                           1                    1           4
24                           0                    5           4
25                           2                    6           2
26                           0                    3           1
27                           0                    2           7
28                           1                    1           6
29                           0                    6           1
...                        ...                  ...         ...
999970                       0                    2           3
999971                       0                    5           7
999972                       0                    2           5
999973                       0                    2           7
999974                       0                    4           2
999975                       0                    5           7
999976                       0                    6           3
999977                       0                    6           5
999978                       1                    4           7
999979                       0                    2           7
999980                       1                    1           5
999981                       1                    1           2
999982                       0                    3           3
999983                       0                    6           0
999984                       0                    1           4
999985                       0                    4           3
999986                       0                    3           7
999987                       0                    5           3
999988                       0                    1           4
999989                       0                    5           1
999990                       0                    4           3
999991                       4                    2           5
999992                       0                    6           1
999993                       0                    3           6
999994                       0                    4           3
999995                       0                    5           4
999996                       0                    6           3
999997                       0                    1           3
999998                       0                    3           1
999999                       0                    5           3

[1000000 rows x 14 columns]>

In [12]:
# split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 0)

print(y_train.value_counts()/len(y_train))

print(y_test.value_counts()/len(y_test))

1    0.500871
0    0.499129
Name: churn_label, dtype: float64
1    0.500587
0    0.499413
Name: churn_label, dtype: float64

In [13]:
# build model

dtc = DecisionTreeClassifier()

dtc.fit(X_train, y_train)
        
y_predict = dtc.predict(X_test)

print('Accracy:', dtc.score(X_test, y_test))
        
print(metrics.accuracy_score(y_test, y_predict))

Accracy: 0.5034133333333334
0.5034133333333334